# Generated by Django 5.1.6 on 2025-02-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='data_nacimento',
            new_name='data_nascimento',
        ),
    ]
